language: python
python:
  - "2.7"
  - "3.6"

env:
  - PLATFORMIO_PROJECT_DIR=examples/hello-world

install:
  - pip install -U https://github.com/platformio/platformio/archive/develop.zip
  - pio pkg install --global --platform symlink://.

script:
  - platformio run -d $PLATFORMIO_PROJECT_DIR

notifications:
  email: false

  slack:
    rooms:
      secure: mpAELqrxd/UEkxPRpTLswEJcBj8EatQOm9fMWgYXqr0vxWRbfxX/TCJnBdK1XCCr2G4Ts/CmGX3aKIZtOABj727zgmHaocxC+UUgym3qdham9AsT9FhHAjn3b87KUP0pnvohoJ9oIgsjmY757VwYRLWDfoHW3j3cvfhYd/bF8UsymuckuZi+9J3E7adx/0DCicPZTAWSBYgfSE14ZzPbRYMlWS6CTClmHeCHWOLymsuBQOvZTFo1MM85nZivZOcQxCplPeq7T0myqA25PeZPtYBvNd2jQTrVrUW8w8cKUGVZ0gpu+5iQTEIRLuQ8JwJuBJhSakt+2cmg/BOKiSMdQPTSfgS7Z3eBCQm/dM/5IEb309UaCeYH27TVr3/m6ZvEjtyUA8U69bDLxTR4LB/rdrXJoTverusVnB5KK20HXUYZ2Dp/125tSFiFJ7ljeGxj2A+MNlm9JEIDHSG0g5d7EF74j3vVA+oYTd9goRnIILiOou+FfL0z0AVX+a5ZM39IO2XHonzAFzjNZwAKAI+SNvSd+DO3UW3x5X3iGYATm8O01cPkRwuDPkxFTdsd5mZ09iDVmDCzYatXi3vsyp7hhUbWYGphTF4ZUoFiuPudMGcvVspmqvZE2wwhDX9weeokwi0jB9hZz9w3HlI/8wkmKlbYUOLg5NFl5RiHdxIBX74=
    on_failure: always
    on_success: change
